<a href="https://colab.research.google.com/github/hectorhh45/tarea_thc1/blob/main/19_oct_2023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
arr1 = np.array((1, 2, 3, 4, 5))

print(arr1)

print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
arr = np.array(42)

print(arr)

42


In [6]:
arr = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]])

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [10]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim,a.shape)
print(b.ndim,b.shape)
print(c.ndim,c.shape)
print(d.ndim,d.shape)

0 ()
1 (5,)
2 (2, 3)
3 (2, 2, 3)


In [11]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [13]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2do elemento de la 1er Fila: ', arr[1, 3])

2do elemento de la 1er Fila:  9


In [16]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[1, 0, 2])

9


In [37]:
# usando numpy:
matriz = np.array([[1, 1, 1],
                  [1, 1, 1],
                  [1, 1, 1]])
suma = np.sum(matriz)
print(suma)

9


In [33]:
# usando listas:
matriz = [[1, 1, 1],
          [1, 1, 1],
          [1, 1, 1]]
suma = 0
for fila in matriz:
    suma += sum(fila)
print(suma)

9


In [35]:
vector1 = np.array([1, 1, 1])
vector2 = np.array([1, 1, 1])
producto_escalar = np.dot(vector1, vector2)
print(producto_escalar)

3


In [38]:
lista1 = [1, 2, 3]
lista2 = [1, 1, 1]
producto_escalar = sum(x * y for x, y in zip(lista1, lista2))
print(producto_escalar)

6
